# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
# 
# Note: This configuration is for cloud database operations only.
# Local development database support has been removed.
project_id = "vibemuse-server"

# Cloud-only migrations configuration
[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]