name: Release (Production)
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # Point the CLI at your cloud project
      - name: Validate Supabase Project ID
        run: |
          if [ -z "$SUPABASE_PROJECT_ID" ]; then
            echo "Error: SUPABASE_PROJECT_ID environment variable is not set"
            exit 1
          fi
          if [ ${#SUPABASE_PROJECT_ID} -ne 20 ]; then
            echo "Error: SUPABASE_PROJECT_ID must be exactly 20 characters long"
            echo "Current length: ${#SUPABASE_PROJECT_ID}"
            exit 1
          fi
          echo "SUPABASE_PROJECT_ID format validation passed"

      - name: Link to Supabase project
        run: supabase link --project-ref "$SUPABASE_PROJECT_ID"

      # Ship every migration in supabase/migrations
      - name: Push database migrations
        run: supabase db push --no-confirm

      # (optional) regenerate TS types against the *remote* DB
      - name: Generate TypeScript types
        run: supabase gen types typescript > types/supabase.ts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd api && npm ci

      # Build and validate the project
      - name: Build project
        run: npm run build

      # Run quick validation tests
      - name: Run linter
        run: npm run lint

      # Commit generated types back to repo if they changed
      - name: Commit generated types
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add types/supabase.ts
          if ! git diff --staged --quiet; then
            git commit -m "chore: update generated Supabase types [skip ci]"
            git push
          else
            echo "No changes to Supabase types"
          fi
